/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cz.fallingfox.matice;

public class App {
    public static void main(String[] args) throws MaticeException {
        Matice m1 = Matice.rng(5, 5, 1, 10);
        Matice m2 = Matice.rng(5, 5, 1, 10);

        IMatice[] ms = m1.switchValues(m2);

        m1.set(10, 10, 0);

        System.out.println(m1);
        System.out.println();
        System.out.println(m2);
        System.out.println();
        System.out.println((Matice) ms[0]);
        System.out.println();
        System.out.println((Matice) ms[1]);
    }
}
